# On push events to the master branch, this workflow will build, test, and create a release
# of the fgdc2iso WAR file.

name: 'Test and (Maybe) Release'

on:
  push:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'

    - name: Copy saxon license to the license file
      run: 'echo "$VAULT_FGDC2ISO_SAXON_LICENSE" > saxon-license.lic'
      env: 
        VAULT_FGDC2ISO_SAXON_LICENSE: ${{ secrets.VAULT_FGDC2ISO_SAXON_LICENSE }}

    - name: Build and run tests
      run: make all
    
    - uses: actions/upload-artifact@v2
      with:
        name: war-file
        path: build/fgdc2iso.war
        if-no-files-found: error
  
  deploy-development:
    # if: github.ref == 'refs/heads/develop'
    name: deploy (development)
    environment: development
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: war-file
          path: build
      - name: deploy
        uses: usds/cloud-gov-cli@master
        with:
          command: push fgdc2iso --vars-file vars.development.yml -p build/fgdc2iso.war --strategy rolling
          org: gsa-datagov
          space: development
          user: ${{secrets.CF_SERVICE_USER}}
          password: ${{secrets.CF_SERVICE_AUTH}}
  
  publish-war:
    if: github.ref == 'refs/heads/main'
    name: 'Publish War File'
    runs-on: ubuntu-latest
    needs: test

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: war-file
        path: build
    - name: Bump version and push tag
      id: bump
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 0.0.0

    - name: Release pushes to main
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/fgdc2iso.war
        tag_name: ${{ steps.bump.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
